awslabs/aws-sdk-android-samples

S3TransferUtilitySample/README.md

Updated the location of Constants.java

Updated README.md

---

AmazonCognitoAuthDemo/app/src/main/java/com/amazonaws/cognito/android/samples/authdemo/MainActivity.java

AmazonCognitoAuthDemo: Added call to set client secret in MainActivity.initCognito()

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoAuthDemo/app/src/main/AndroidManifest.xml
AmazonCognitoAuthDemo/app/src/main/java/com/amazonaws/cognito/android/samples/authdemo/MainActivity.java
AmazonCognitoAuthDemo/build.gradle
AmazonCognitoAuthDemo/gradle/wrapper/gradle-wrapper.properties

Fix error message to not cause crash
Update TODO in AndroidManifest to clarify

Update gradle to 4.4

---

AndroidPubSub/README.md

Minor spelling fixes and changes based on AWS console changes

Updated PubSub readme

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AmazonKinesisVideoDemoApp/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle
[DEPRECATED] CreateIotCertWithCSR/build.gradle
[DEPRECATED] TemperatureControl/build.gradle

update aws sdk version for sample apps to 2.9.x

update aws sdk version for sample apps to 2.9.x

---

AndroidPubSub/README.md

Update instructions to use awsconfiguration.json

Update AndroidPubSub README.md

---

S3TransferUtilitySample/src/androidTest/java/com/amazonaws/demo/s3transferutility/TestMainActivity.java

Increase waittime for s3 test from 1 second to 1 minute

Increase waittime for s3 test from 1 second to 1 minute

---

S3TransferUtilitySample/build.gradle
S3TransferUtilitySample/src/androidTest/java/com/amazonaws/demo/s3transferutility/TestMainActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/DownloadActivity.java

1. Before download, set write permission 
2. add code to tap allow button  for ui test

Fix write deny issue for S3 download

---

AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/KinesisVideoDemoApp.java

Adds a latch to ensure that the credentials provider was initialized before proceeding to the app.

Add latch for KinesisVideo sample app

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle

Update sample apps to use 2.12.+ version of the SDK

Bump sample applications versions to 2.12.+

---

AmazonKinesisVideoDemoApp/README.md

Instructions reference line number that keeps changing.

[KinesisVideo] Update README.md

---

AmazonCognitoAuthDemo/README.md

Fix typo in README.md

---

AndroidPubSubWebSocket/build.gradle
AndroidPubSubWebSocket/gradle/wrapper/gradle-wrapper.properties

Update gradle version for AndroidPubSubWebsocket

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle

Update sample apps to use 2.13.+ version of the SDK

Bump sample applications versions to 2.13.+

---

LexSample/app/src/main/java/com/amazonaws/sample/lex/InteractiveVoiceActivity.java
LexSample/app/src/main/java/com/amazonaws/sample/lex/TextActivity.java
LexSample/app/src/main/java/com/amazonaws/sample/lex/TextMessage.java
LexSample/build.gradle
LexSample/gradle/wrapper/gradle-wrapper.properties

Lex sample update

---

AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle

Fix build.gradle files for IoT samples

---

AndroidPubSub/README.md
AndroidPubSub/build.gradle
AndroidPubSub/gradle/wrapper/gradle-wrapper.properties

https://github.com/aws-amplify/aws-sdk-android/issues/1004

Update Android PubSub to be compatible with latest Android Studio

---

AndroidPubSubWebSocket/README.md
AndroidPubSubWebSocket/build.gradle
AndroidPubSubWebSocket/gradle/wrapper/gradle-wrapper.properties

Update gradle and android gradle plugin to the latest

---

AmazonCognitoAuthDemo/app/src/main/AndroidManifest.xml

https://github.com/aws-amplify/docs/issues/752

[CognitoAuth] Fix android scheme, host and redirect in AndroidManifest.xml

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle

Update sample apps to use 2.14.+ version of the SDK

Bump sample applications versions to 2.14.+

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle

Update sample apps to use 2.15.+ version of the SDK

Bump sample applications versions to 2.15.+

---

AmazonCognitoAuthDemo/app/build.gradle
AmazonCognitoYourUserPoolsDemo/app/build.gradle
AndroidPubSub/build.gradle
AndroidPubSubWebSocket/build.gradle
LexSample/app/build.gradle
PollyDemo/app/build.gradle
S3TransferUtilitySample/build.gradle

Update sample apps to use 2.16.+ version of the SDK

Bump sample applications versions to 2.16.+

---

AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/AppHelper.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/ChooseMFA.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/FirstTimeLoginAttributesDisplayAdapter.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/ForgotPasswordActivity.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/MFAActivity.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/NewPassword.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/RegisterUser.java
AmazonCognitoYourUserPoolsDemo/app/src/main/java/com/amazonaws/youruserpools/VerifyActivity.java

Update the cognito userpools sample

---

S3TransferUtilitySample/AndroidManifest.xml
S3TransferUtilitySample/build.gradle
S3TransferUtilitySample/gradle/wrapper/gradle-wrapper.properties
S3TransferUtilitySample/res/layout/activity_download.xml
S3TransferUtilitySample/res/layout/activity_upload.xml
S3TransferUtilitySample/src/androidTest/java/com/amazonaws/demo/s3transferutility/DownloadCompleteIdlingResource.java
S3TransferUtilitySample/src/androidTest/java/com/amazonaws/demo/s3transferutility/TestMainActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/DownloadActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/DownloadSelectionActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/MainActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/MyApplication.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/MyService.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/UploadActivity.java
S3TransferUtilitySample/src/com/amazonaws/demo/s3transferutility/Util.java

- fixed bug where irrelevant `DownloadListener` was imported, causing namespace conflict with a nested class with the same name
- gradle wrapper version bump
- dependencies version bump
- lower min SDK from 23 to 18
- It seems that it was originally set that way under an the assumption that `AWSMobileClient` dependency requires minSdk>23
- UI fixes
- `UPLOAD A FILE` button is now aligned with the rest
- `DOWNLOAD` and `DOWNLOAD IN BACKGROUND` are now in a single row
- add + update license header on source files
- miscellaneous code clean up 

Clean up code

---

.github/CODEOWNERS

Create CODEOWNERS file to participate in branch restrictions

chore: Create CODEOWNERS file [skip ci]

---

AmazonKinesisVideoDemoApp/README.md

Help users setup the sample app quicker by linking additional resources and providing an example awsconfiguration.json, to make it easier for users to keep track of what goes where.

KVS Sample: Update Readme

---

AmazonKinesisVideoDemoApp/README.md
AmazonKinesisVideoDemoApp/build.gradle
AmazonKinesisVideoDemoApp/gradle/wrapper/gradle-wrapper.properties
AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/fragment/StreamConfigurationFragment.java

**Description of changes:**
Update the readme, gradle version bumped, and a fix app crashing when closing/re-opening after being signing in.
**Testing**
Followed the instructions, and run the sample both on an emulator (Pixel 3a API 33), and also real devices (Samsung Galaxy S9+, Samsung S22 Ultra) to confirm that it is working.
* Tested in both us-west-2 and ap-south-1 regions.
* Also closed the app while being signed in and reopened it.

Update user pool and identity pool instructions, bump gradle version
